Add `template` to FixedMatrix::row() declaration
The standard requires `template` for dependent template names used in
definitions and permits it in definitions. Using `template` in the
definition but not the declaration seems to confuse MSVC, though:

    numerics/fixed_arrays_body.hpp(125): error C2244: 'principia::numerics::internal_fixed_arrays::FixedMatrix<Scalar,rows,columns>::row': unable to match function definition to an existing declaration.